### ISSUE TITLE
OPTIONS request should not have body

### ISSUE THREAD

**Issue by laurentsebag** [mvemjsun/mock_server#3]
When mocking a request and selection a request type of OPTIONS, the body/payload should be disabled as it's not standard to have body for OPTIONS requests.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

**Comment by mvemjsun** [comment]
`Successful response has body - YES` @laurentsebag

**Comment by laurentsebag** [comment]
My bad, I hadn't read this properly and assumed they never had body for responses.
